### ISSUE TITLE
Is it possible to have a release version ??

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-orientdb#17]

**Comment by barjo** [comment]
Hi, 

The last release of `wisdom-orientdb` has been made 23 days ago. You can see the last release [here](https://github.com/wisdom-framework/wisdom-orientdb/releases). 

Release are deployed on the maven central and sonatype repositories as well as on the github release page.

Here is the last release dependency declaration:

```
<dependency>
  <groupId>org.wisdom-framework</groupId>
  <artifactId>wisdom-orientdb-object</artifactId>
  <version>0.2.2</version>
</dependency>
```

**Comment by hboumedane** [comment]
what are the differences between the snapshot and the release version ?

**Comment by cescoffier** [comment]
From https://github.com/wisdom-framework/wisdom-orientdb/commits/master almost no differences.

**Comment by hboumedane** [comment]
thanks for the help !!
