### ISSUE TITLE
models not persisted in db

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-orientdb#24]
I have two models mapped with oneToMany relation. when I try to persist the model that hold the relation, nothing happen in the DB (no record in the db). I don't have any error !!

```java
     @Model(value = XXXXX.class)
      private OrientDbCrud<XXXXX,String> _listCrud;


        Event log = new Event();
        log.setEvent(event);

        List<Event> logs = table.getEvents();
        logs.add(log);

        table.setEvents(logs);
        _listCrud.save(table);
```

**Comment by barjo** [comment]
Hi, can you tell me more about the two models, if possible giving an equivalent example so that I can reproduce your issue.

**Comment by hboumedane** [comment]
here an exemple of my models :   
http://pastebin.com/Aw5F0spj

**Comment by barjo** [comment]
It seems related to #23 
can you try without the `_` convention as prefix of the model class field.

**Comment by hboumedane** [comment]
thanks for your help your were wright.
it's working now.

**Comment by barjo** [comment]
Duplicate with #23
