### ISSUE TITLE
Remote DB

### ISSUE THREAD

**Issue by mxmind** [wisdom-framework/wisdom-orientdb#26]
Please provide information, how to connect to remote db, not to embedded.

**Comment by barjo** [comment]
Hi @mxmind, you can find information related to the configuration in the [readme](https://github.com/wisdom-framework/wisdom-orientdb/blob/master/README.md). 

You can also have a look at orientdb database url [documentation](http://orientdb.com/docs/last/Concepts.html#database). A valid url for a remote db would be `remote:localhost/todolist` for example. Where localhost is the host of the running orientdb server, and todolist the name of the db.

**Comment by mxmind** [comment]
Thank you

From:  Jonathan Bardin
Reply-To:  wisdom-framework/wisdom-orientdb
Date:  Monday, June 15, 2015 at 6:24 AM
To:  wisdom-framework/wisdom-orientdb
Cc:  Volodymyr Zdomishchuk
Subject:  Re: [wisdom-orientdb] Remote DB (#26)


Hi @mxmind, you can find information related to the configuration in the readme. 

You can also have a look at orientdb database url documentation. A valid url for a remote db would be remote:localhost/todolist for example. Where localhost is the host of the running orientdb server, and todolist the name of the db.
